apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app
  # LoadBalancer exposes the service externally
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
